-- new table for help text

CREATE TABLE HELP_TEXT_ITEMS
(
  ID NUMBER NOT NULL,
  BLOB_VALUE BLOB NOT NULL,
  VERSION NUMBER
)
/

-- constraints and indexes

ALTER TABLE HELP_TEXT_ITEMS
 ADD (CONSTRAINT HELP_TEXT_PK PRIMARY KEY
  (ID))
/

-- add constraint

ALTER TABLE HELP_TEXT_ITEMS ADD (CONSTRAINT
 DA_HTI_FK FOREIGN KEY
  (ID) REFERENCES DYNAMIC_ATTRIBUTES
  (ID) ON DELETE CASCADE)
/

-- add UID column to dynamic attribute table and modify constraint
ALTER TABLE DYNAMIC_ATTRIBUTES ADD UNIQUE_NUMBER NUMBER;

ALTER TABLE DYNAMIC_ATTRIBUTES DROP CONSTRAINT ZDT_DA_UNIQUE_UK;

ALTER TABLE DYNAMIC_ATTRIBUTES
 ADD (CONSTRAINT ZDT_DA_UNIQUE_UK UNIQUE
  (LABEL
  ,UNIQUE_NUMBER
  ,ARTEFACT_TYPE
  ,QD_ID))
/

ALTER TABLE QUE_WORKFLOWS
 ADD (CONSTRAINT QUWFLL_UK UNIQUE
  (LABEL))
/

-- permits
UPDATE PERMITS SET URL = '/admin/editquestion.*.htm' WHERE URL = '/admin/editquestionnaire.*.htm';
UPDATE PERMITS SET URL = '/admin/viewquestion.*.htm' WHERE URL = '/admin/viewquestionnaire.*.htm';

ALTER TABLE REPORT_COLUMNS MODIFY (REF_VALUE VARCHAR2(1000) )
/

CREATE SEQUENCE DA_REF_SQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE;
 /

ALTER TABLE DYNAMIC_ATTRIBUTES ADD (
	IS_DYNAMIC  VARCHAR2(1 BYTE)  DEFAULT 'F'
);
/

 CREATE TABLE DYNAMIC_ATTR_REFERENCES
(
  ID NUMBER NOT NULL,
  LABEL VARCHAR2(100),
  TYPE VARCHAR2(50) NOT NULL,
  UPPER_BOUND NUMBER,
  LOWER_BOUND NUMBER,
  REFERENCE_DA_ID NUMBER,
  PARENT_DA_ID NUMBER,
  PARENT_MAPPING_ID NUMBER
);
/

ALTER TABLE DYNAMIC_ATTR_REFERENCES
 ADD (CONSTRAINT DA_REFERENCES_PK PRIMARY KEY
  (ID));
/

ALTER TABLE DYNAMIC_ATTR_REFERENCES ADD (CONSTRAINT
 DA_REF_FK FOREIGN KEY
  (REFERENCE_DA_ID) REFERENCES DYNAMIC_ATTRIBUTES
  (ID));
/

ALTER TABLE DYNAMIC_ATTR_REFERENCES ADD (CONSTRAINT
 DA_PA_REF_FK FOREIGN KEY
  (PARENT_DA_ID) REFERENCES DYNAMIC_ATTRIBUTES
  (ID));
/

ALTER TABLE DYNAMIC_ATTR_REFERENCES ADD (CONSTRAINT
 PA_DA_REF_FK FOREIGN KEY
  (PARENT_MAPPING_ID) REFERENCES DYNAMIC_ATTR_REFERENCES
  (ID));
/

CREATE INDEX DA_DAR_PA_FK_I ON DYNAMIC_ATTR_REFERENCES
 (PARENT_DA_ID);
/

CREATE INDEX DA_DAR_REF_FK_I ON DYNAMIC_ATTR_REFERENCES
 (REFERENCE_DA_ID);
/

ALTER TABLE NODE_DAS ADD DYNAMIC_POSITION NUMBER;

ALTER PACKAGE ZYNAP_DA_SP COMPILE BODY;
@packages/zynap_loader_body.sql;

COMMIT;

