--------------------------------------------------------
-- 09/11/09
--------------------------------------------------------

prompt
prompt **************************** HAVE YOU BACKED UP YOUR DATABASE (Y/N)? ********************************************
prompt
accept l_yes char prompt 'db backed up (y/n): '

ALTER TABLE PREFERENCE_GROUPS DROP CONSTRAINT PREFGPS_GP_FK;

ALTER TABLE PREFERENCE_GROUPS ADD (CONSTRAINT
 PREFGPS_GP_FK FOREIGN KEY
  (GROUP_ID) REFERENCES GROUPS
  (ID) ON DELETE CASCADE)
/

ALTER TABLE PREFERENCE_GROUPS DROP CONSTRAINT PREFGPS_RP_FK;

PROMPT Creating Foreign Key on 'PREFERENCE_GROUPS'
ALTER TABLE PREFERENCE_GROUPS ADD (CONSTRAINT
 PREFGPS_RP_FK FOREIGN KEY
  (PREFERENCE_ID) REFERENCES PREFERENCES
  (ID) ON DELETE CASCADE)
/

ALTER TABLE POPULATION_GROUPS DROP CONSTRAINT PPGPS_GP_FK;

PROMPT Creating Foreign Key on 'POPULATION_GROUPS'
ALTER TABLE POPULATION_GROUPS ADD (CONSTRAINT
 PPGPS_GP_FK FOREIGN KEY
  (GROUP_ID) REFERENCES GROUPS
  (ID) ON DELETE CASCADE)
/

ALTER TABLE POPULATION_GROUPS DROP CONSTRAINT PPGPS_RP_FK;

PROMPT Creating Foreign Key on 'POPULATION_GROUPS'
ALTER TABLE POPULATION_GROUPS ADD (CONSTRAINT
 PPGPS_RP_FK FOREIGN KEY
  (POPULATION_ID) REFERENCES POPULATIONS
  (ID) ON DELETE CASCADE)
/

ALTER TABLE REPORT_GROUPS DROP CONSTRAINT RPGPS_GP_FK;

ALTER TABLE REPORT_GROUPS ADD (CONSTRAINT
 RPGPS_GP_FK FOREIGN KEY
  (GROUP_ID) REFERENCES GROUPS
  (ID) ON DELETE CASCADE)
/

ALTER TABLE REPORT_GROUPS DROP CONSTRAINT RPGPS_RP_FK;

ALTER TABLE REPORT_GROUPS ADD (CONSTRAINT
 RPGPS_RP_FK FOREIGN KEY
  (REPORT_ID) REFERENCES REPORTS
  (ID) ON DELETE CASCADE)
/

ALTER TABLE AREAS ADD POSITION_POPULATION_ID INTEGER;
ALTER TABLE AREAS ADD SUBJECT_POPULATION_ID INTEGER;

ALTER TABLE AREAS ADD (CONSTRAINT
 A_PP_FK FOREIGN KEY
  (POSITION_POPULATION_ID) REFERENCES POPULATIONS
  (ID))
/

ALTER TABLE AREAS ADD (CONSTRAINT
 A_SP_FK FOREIGN KEY
  (SUBJECT_POPULATION_ID) REFERENCES POPULATIONS
  (ID))
/

ALTER TABLE AREA_ELEMENTS ADD IS_FROM_POPULATION VARCHAR(1) DEFAULT 'F';

-- compile in the stored procedures
@packages/zynap_wf_integration_spec.sql
@packages/zynap_wf_integration_body.sql

ALTER PACKAGE wf_integration COMPILE SPECIFICATION;
ALTER PACKAGE wf_integration COMPILE BODY;

commit;
