PROMPT EXTRA INFORMATION FOR VERSION 4.6.4 9 BOX GRIDS

prompt
prompt **************************** HAVE YOU BACKED UP YOUR DATABASE (Y/N)? ********************************************
prompt
accept l_yes char prompt 'db backed up (y/n): '

CREATE TABLE CROSSTAB_CELL_INFO (
 ID NUMBER NOT NULL
,VERTICAL_VALUE_ID NUMBER NOT NULL
,HORIZONTAL_VALUE_ID NUMBER NOT NULL
,CROSSTAB_ID NUMBER NOT NULL
,LABEL VARCHAR2 (2000)
)
/

ALTER TABLE CROSSTAB_CELL_INFO
 ADD (CONSTRAINT CT_CELL_PK PRIMARY KEY
  (ID))
/

ALTER TABLE CROSSTAB_CELL_INFO ADD (CONSTRAINT
 CT_CI_FK FOREIGN KEY
  (CROSSTAB_ID) REFERENCES REPORTS
  (ID))
/

commit;