@packages/zynap_da_spec.sql
@packages/zynap_da_body.sql 

-- recompile package
ALTER PACKAGE ZYNAP_DA_SP COMPILE SPECIFICATION;
ALTER PACKAGE ZYNAP_DA_SP COMPILE BODY;
ALTER PACKAGE ZYNAP_LOADER_SP COMPILE BODY;

ALTER TABLE DYNAMIC_ATTRIBUTES ADD (IS_CALCULATED VARCHAR2(1) DEFAULT 'F');
ALTER TABLE DYNAMIC_ATTRIBUTES ADD (CALCULATION_ID NUMBER);

EXEC zynap_da_sp.add_attribute('Current Date', 'DATE', 'FUNC', NULL, NULL, 'F', 'T', 'F', NULL, 'Date determined at time of execution');

UPDATE DYNAMIC_ATTRIBUTES SET MODIFIED_LABEL = replace(trim(lower(label)),' ') WHERE DYNAMIC_ATTRIBUTES.artefact_type='FUNC';
INSERT INTO UPGRADE_STATUS (DATE_EXECUTED, SCRIPT_VERSION, SCRIPT_LINE_NUMBER, COMMENTS) VALUES(SYSDATE, 'upgrade4.5.7-4.5.8.sql', 13, 'Insert current date attribute for functions');

-- SEQUENCE
CREATE SEQUENCE CALCULATION_SQ
    NOMAXVALUE NOMINVALUE NOCYCLE
/

CREATE TABLE CALCULATIONS
(
   ID NUMBER NOT NULL
  ,TYPE VARCHAR2 (100) NOT NULL
  ,FORMAT INTEGER
)
/

CREATE TABLE CALCULATION_EXPRESSIONS
(
   ID NUMBER NOT NULL
  ,CALCULATION_ID NUMBER NOT NULL
  ,ATTRIBUTE NUMBER
  ,VALUE VARCHAR2 (400)
  ,FORMAT INTEGER DEFAULT 0
  ,OPERATOR VARCHAR2 (4)
  ,POSITION NUMBER NOT NULL
  ,BRACKET VARCHAR2 (1)
  ,REF_VALUE VARCHAR2 (2000)
)
/

PROMPT Creating index on 'CALCULATION_EXPRESSIONS' CALCULATION_ID
CREATE INDEX CALC_EXP_FK_I ON CALCULATION_EXPRESSIONS
 (CALCULATION_ID)
/

PROMPT Creating Primary Key on 'CALCULATIONS'
ALTER TABLE CALCULATIONS
 ADD (CONSTRAINT CALC_PK PRIMARY KEY
  (ID))
/

PROMPT Creating Primary Key on 'CALCULATION_EXPRESSIONS'
ALTER TABLE CALCULATION_EXPRESSIONS
 ADD (CONSTRAINT CALC_EXP_PK PRIMARY KEY
  (ID))
/

PROMPT Creating Foreign Key on 'CALCULATION_EXPRESSIONS'
ALTER TABLE CALCULATION_EXPRESSIONS ADD (CONSTRAINT
 CALC_EXP_1_FK FOREIGN KEY
  (CALCULATION_ID) REFERENCES CALCULATIONS
  (ID))
/

PROMPT Creating Foreign Key on 'CALCULATION_EXPRESSIONS'
ALTER TABLE CALCULATION_EXPRESSIONS ADD (CONSTRAINT
 CALC_EXP_ATTR_1_FK FOREIGN KEY
  (ATTRIBUTE) REFERENCES DYNAMIC_ATTRIBUTES
  (ID))
/

PROMPT Creating Foreign Key on 'DYNAMIC_ATTRIBUTES'
ALTER TABLE DYNAMIC_ATTRIBUTES ADD (CONSTRAINT
 ZDA_CALC_FK_1 FOREIGN KEY
  (CALCULATION_ID) REFERENCES CALCULATIONS
  (ID))
/

ALTER TABLE DYNAMIC_ATTRIBUTES MODIFY LABEL VARCHAR2(1000); 
ALTER TABLE DYNAMIC_ATTRIBUTES MODIFY DESCRIPTION VARCHAR2(4000); 
ALTER TABLE DYNAMIC_ATTRIBUTES MODIFY MODIFIED_LABEL VARCHAR2(1000);

ALTER TABLE QUE_DEFINITIONS MODIFY LABEL VARCHAR2(1000);
ALTER TABLE QUE_DEFINITIONS MODIFY DESCRIPTION VARCHAR2(1000);

ALTER TABLE PERFORMANCE_REVIEWS MODIFY LABEL VARCHAR2(500);

-- recompile
ALTER PACKAGE WF_INTEGRATION COMPILE SPECIFICATION;
ALTER PACKAGE WF_INTEGRATION COMPILE BODY;

ALTER PACKAGE ZYNAP_AUTH_SP COMPILE SPECIFICATION;
ALTER PACKAGE ZYNAP_AUTH_SP COMPILE BODY;

ALTER PACKAGE ZYNAP_DA_SP COMPILE SPECIFICATION;
ALTER PACKAGE ZYNAP_DA_SP COMPILE BODY;

ALTER PACKAGE ZYNAP_LOADER_SP COMPILE SPECIFICATION;
ALTER PACKAGE ZYNAP_LOADER_SP COMPILE BODY;

PROMPT ******** PLEASE NOW RUN THE REPORT UPGRADER (JUST ASK YOUR LOCAL FRIENDLY PROGRAMMER) ************

COMMIT;