--------------------------------------------------------
-- 03/04/09
--------------------------------------------------------

prompt
prompt **************************** HAVE YOU BACKED UP YOUR DATABASE (Y/N)? ********************************************
prompt
accept l_yes char prompt 'db backed up (y/n): '

-- multiple choice
insert into lookup_values (id, type_id, value_id, SHORT_DESC, DESCRIPTION, IS_ACTIVE, IS_SYSTEM, SORT_ORDER)
VALUES (LOOKUPVALUE_SQ.NEXTVAL, 'DATYPE', 'MULTISELECT', 'Multi Selection List', 'Multiple choice drop-down selection list', 'T', 'T', 10);

ALTER TABLE POPULATIONS ADD ACTIVE_CRITERIA INTEGER DEFAULT 1;

-- create a default inactive all people and inactive all positions?

ALTER TABLE area_elements ADD is_excluded varchar(1) DEFAULT 'F';
ALTER TABLE REPORTS ADD DECIMAL_PLACES INTEGER DEFAULT 0;
ALTER TABLE REPORTS ADD DISPLAY_OPTION INTEGER DEFAULT 0;

CREATE TABLE REPORT_GROUPS
 (
  REPORT_ID NUMBER NOT NULL
 ,GROUP_ID NUMBER NOT NULL
 )
/

PROMPT Creating Primary Key on 'REPORT_GROUPS'
ALTER TABLE REPORT_GROUPS
 ADD (CONSTRAINT RGPS_PK PRIMARY KEY
  (REPORT_ID
  ,GROUP_ID))
/

PROMPT Creating Foreign Key on 'REPORT_GROUPS'
ALTER TABLE REPORT_GROUPS ADD (CONSTRAINT
 RPGPS_GP_FK FOREIGN KEY
  (GROUP_ID) REFERENCES GROUPS
  (ID))
/

PROMPT Creating Foreign Key on 'REPORT_GROUPS'
ALTER TABLE REPORT_GROUPS ADD (CONSTRAINT
 RPGPS_RP_FK FOREIGN KEY
  (REPORT_ID) REFERENCES REPORTS
  (ID))
/

PROMPT Creating Index ON 'REPORT_GROUPS'
CREATE INDEX RPGPS_GP_FK_2 ON REPORT_GROUPS
 (GROUP_ID)
/

PROMPT Creating Index ON 'REPORT_GROUPS'
CREATE INDEX RPGPS_RP_FK_2 ON REPORT_GROUPS
 (REPORT_ID)
/

CREATE TABLE PREFERENCE_GROUPS
 (
  PREFERENCE_ID NUMBER NOT NULL
 ,GROUP_ID NUMBER NOT NULL
 )
/

PROMPT Creating Primary Key on 'PREFERENCE_GROUPS'
ALTER TABLE PREFERENCE_GROUPS
 ADD (CONSTRAINT PGPS_PK PRIMARY KEY
  (PREFERENCE_ID
  ,GROUP_ID))
/

PROMPT Creating Foreign Key on 'PREFERENCE_GROUPS'
ALTER TABLE PREFERENCE_GROUPS ADD (CONSTRAINT
 PREFGPS_GP_FK FOREIGN KEY
  (GROUP_ID) REFERENCES GROUPS
  (ID))
/

PROMPT Creating Foreign Key on 'PREFERENCE_GROUPS'
ALTER TABLE PREFERENCE_GROUPS ADD (CONSTRAINT
 PREFGPS_RP_FK FOREIGN KEY
  (PREFERENCE_ID) REFERENCES PREFERENCES
  (ID))
/

PROMPT Creating Index ON 'PREFERENCE_GROUPS'
CREATE INDEX PREFGPS_GP_IDX_2 ON PREFERENCE_GROUPS
 (GROUP_ID)
/

PROMPT Creating Index ON 'PREFERENCE_GROUPS'
CREATE INDEX PREFGPS_RP_IDX_2 ON PREFERENCE_GROUPS
 (PREFERENCE_ID)
/

@views/security_views.sql;

commit;
