PROMPT EXTRA INFORMATION FOR VERSION 4.6.4

prompt
prompt **************************** HAVE YOU BACKED UP YOUR DATABASE (Y/N)? ********************************************
prompt
accept l_yes char prompt 'db backed up (y/n): '

DELETE FROM SESSION_LOGS;
DELETE FROM SESSIONS_OPENED;
ALTER TABLE SESSION_LOGS ADD ID NUMBER NOT NULL;
ALTER TABLE SESSIONS_OPENED DROP CONSTRAINT SOD_ZSLT_FK;
ALTER TABLE SESSION_LOGS DROP CONSTRAINT ZSLT_PK;
ALTER TABLE SESSIONS_OPENED DROP COLUMN SESSION_ID;
ALTER TABLE SESSIONS_OPENED ADD SESSION_ID NUMBER;


ALTER TABLE SESSION_LOGS
ADD (CONSTRAINT ZSLT_PK PRIMARY KEY
(ID))
/

ALTER TABLE SESSIONS_OPENED ADD (CONSTRAINT
SOD_ZSLT_FK FOREIGN KEY
(SESSION_ID) REFERENCES SESSION_LOGS
(ID) ON DELETE CASCADE)
/

@upgrades/zynap_triggers_hierarchy_4.6.4--.sql

commit;
