Set define off;

-- add description column for preferences
ALTER TABLE PREFERENCES ADD DESCRIPTION VARCHAR2(500);

-- add new columns for cross tab artefact views
ALTER TABLE REPORTS ADD CROSSTAB_VIEW_REPORT_ID NUMBER;

ALTER TABLE REPORTS ADD DISPLAY_LIMIT NUMBER;

PROMPT Creating Foreign Key on 'REPORTS'
ALTER TABLE REPORTS ADD (CONSTRAINT
 REP_CROSSTABVIEWREP_FK FOREIGN KEY
  (CROSSTAB_VIEW_REPORT_ID) REFERENCES REPORTS
  (ID))
/

COMMIT;