#!/bin/sh

if [ -z "$1" -o -z "$3" ]
then
	echo usage $0 [DB Admin User] [DB Admin password] [DB User] [Dump file name, no ending]
	exit 2
fi

set -u

DBADMIN=$1
DBPASS=$2
DBUSER=$3
DMPFILE=$4


if [ -z "$ORACLE_HOME" ]
then
	echo Please ensure ORACLE_HOME environment variable is set.
	echo E.g. ORACLE_HOME=/home/oracle/product/9.2.0.4.0
	exit 3
fi

# Create TS user

sqlplus $DBADMIN/$DBPASS @promptAndCreateUser.sql <<XXX
${DBUSER}
XXX

result=$?
echo RESULT = $result

if [ "$result" -ne 0 ]
then
	echo ****** User creation failed *******
	exit $result
fi

# Import the TS schema and data

impdp system/$DBPASS SCHEMAS=TME remap_schema=TME:blueprint \
            directory=DATA_PUMP_DIR \
            dumpfile=$DMPFILE.dmp logfile=$DMPFILE_restore.log

#$ORACLE_HOME/bin/imp $DBUSER/$DBUSER LOG=${DMPFILE}/ts_restore.log FULL=y COMMIT=y ROWS=y INDEXES=y CONSTRAINTS=y GRANTS=y FILE=${DMPFILE}/ts.dmp
result=$?

echo RESULT = $result

if [ "$result" -ne 0 ]
then
	echo ****** Database restore failed *******
	exit $result
fi

echo Restore completed OK.
